Traceback (most recent call last):
  File "convertNumber.py", line 95, in <module>
    if (int(sys.argv[3]) == 1):
IndexError: list index out of range
